# Generated by Django 5.2.17 on 2026-09-24 11:19

import core.models
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('robotics', 'Robotics'), ('frontend', 'Programming: Frontend'), ('backend', 'Programming: Backend'), ('fusion360', '3D modeling: Fusion 360'), ('blender', '3D modeling: Blender')], db_index=True, max_length=20, verbose_name='direction')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('title_ru', models.CharField(max_length=160, verbose_name='title (RU)')),
                ('title_ky', models.CharField(blank=True, max_length=160, verbose_name='title (KY)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='title (EN)')),
                ('short_ru', models.CharField(blank=True, max_length=300, verbose_name='short description (RU)')),
                ('short_ky', models.CharField(blank=True, max_length=300, verbose_name='short description (KY)')),
                ('short_en', models.CharField(blank=True, max_length=300, verbose_name='short description (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='full description (RU)')),
                ('description_ky', models.TextField(blank=True, verbose_name='full description (KY)')),
                ('description_en', models.TextField(blank=True, verbose_name='full description (EN)')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='level')),
                ('age_from', models.PositiveSmallIntegerField(default=10, verbose_name='age from')),
                ('age_to', models.PositiveSmallIntegerField(default=17, verbose_name='age to')),
                ('duration_months', models.PositiveSmallIntegerField(default=6, verbose_name='duration, months')),
                ('lessons_per_week', models.PositiveSmallIntegerField(default=2, verbose_name='lessons per week')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price, KGS per month')),
                ('cover', models.ImageField(blank=True, upload_to='courses/', verbose_name='cover')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='teachers')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['order', 'title_ru'],
            },
            bases=(core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('phone', models.CharField(max_length=32, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(99)], verbose_name='age')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=12, verbose_name='status')),
                ('manager_note', models.TextField(blank=True, verbose_name='manager note')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='received')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.course', verbose_name='course')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL, verbose_name='handled by')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to=settings.AUTH_USER_MODEL, verbose_name='student account')),
            ],
            options={
                'verbose_name': 'enrollment request',
                'verbose_name_plural': 'enrollment requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('weekdays', models.CharField(blank=True, help_text='Comma-separated numbers: 0 = Monday … 6 = Sunday.', max_length=20, verbose_name='days of week')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('room', models.CharField(blank=True, max_length=60, verbose_name='room')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='start date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.course', verbose_name='course')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='study_groups', to=settings.AUTH_USER_MODEL, verbose_name='students')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='lesson number')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('video_file', models.FileField(blank=True, upload_to='lessons/video/%Y/%m/', validators=[core.models.validate_video_file], verbose_name='video file')),
                ('youtube_url', models.URLField(blank=True, validators=[core.models.validate_youtube_url], verbose_name='YouTube link')),
                ('materials', models.FileField(blank=True, upload_to='lessons/materials/%Y/%m/', verbose_name='materials')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.course', verbose_name='course')),
                ('group', models.ForeignKey(blank=True, help_text='Leave empty to show the lesson to all groups of the course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='core.group', verbose_name='group')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'video lesson',
                'verbose_name_plural': 'video lessons',
                'ordering': ['course', 'number', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='title (RU)')),
                ('title_ky', models.CharField(blank=True, max_length=200, verbose_name='title (KY)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='title (EN)')),
                ('body_ru', models.TextField(verbose_name='text (RU)')),
                ('body_ky', models.TextField(blank=True, verbose_name='text (KY)')),
                ('body_en', models.TextField(blank=True, verbose_name='text (EN)')),
                ('image', models.ImageField(blank=True, upload_to='news/', verbose_name='image')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='publication date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'news item',
                'verbose_name_plural': 'news',
                'ordering': ['-is_pinned', '-published_at'],
            },
            bases=(core.models.TranslatableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('excused', 'Excused')], default='present', max_length=10, verbose_name='status')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='grade')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='comment')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='marked by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance',
                'ordering': ['-date', 'student__last_name'],
                'unique_together': {('group', 'student', 'date')},
            },
        ),
    ]
